%YAML:1.0

# Camera Parameters. Adjust them!

# Camera calibration parameters (OpenCV) 
Camera.fx: 371.975264
Camera.fy: 372.163582
Camera.cx: 315.632343
Camera.cy: 250.592551

Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0

# Camera frames per second 
Camera.fps: 23.8

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

#--------------------------------------------------------------------------------------------
### Changing the parameters below could seriously degradate the performance of the system

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold (lower less restrictive)			
ORBextractor.fastTh: 20

# ORB Extractor: Score to sort features. 0 -> Harris Score, 1 -> FAST Score			
ORBextractor.nScoreType: 1


# Constant Velocity Motion Model (0 - disabled, 1 - enabled [recommended])
UseMotionModel: 1
